### ISSUE TITLE
Fix HomeAssistant deprecation warning

### ISSUE THREAD

**Issue by uhppoted** [uhppoted/uhppoted-app-home-assistant#11]
> 2024-11-27 16:31:58 2024-11-27 16:31:58.597 WARNING (MainThread) [homeassistant.helpers.frame] Detected
> that custom integration 'uhppoted' calls async_forward_entry_setup for integration, uhppoted with title: uhppoted
> and entry_id: 01JDR2RQ3TBNXC3KSBH487VZ35, which is deprecated and will stop working in Home Assistant
> 2025.6, await async_forward_entry_setups instead at custom_components/uhppoted/__init__.py, line 93: 
> hass.async_create_task(hass.config_entries.async_forward_entry_setup(entry, "sensor")), please report it to 
> the author of the 'uhppoted' custom integration

> 2024-11-27 16:31:59 2024-11-27 16:31:59.206 WARNING (ImportExecutor_0) [homeassistant.const] 
> TIME_SECONDS was used from uhppoted, this is a deprecated constant which will be removed in 
> HA Core 2025.1. Use UnitOfTime.SECONDS instead, please report it to the author of the 'uhppoted' custom
> integration
> 2024-11-27 16:31:59 2024-11-27 16:31:59.216 INFO (MainThread) [homeassistant.components.sensor] Setting up uhppoted.sensor

**Comment by twystd** [comment]
Closing - rolled into fixes for https://github.com/uhppoted/uhppoted-app-home-assistant/issues/12
